version: '3'
services:
  nextjs:
    container_name: nextjs
    build:
      context: ./
    env_file:
      - ./.env
      - ./.env.local
    ports:
      - 3000:3000
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - 80:80
