version: "3"

services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER:-spaceman}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-spaceman}
      POSTGRES_DB: movietracker
  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
