version: '3'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: spaceman
      POSTGRES_PASSWORD: spaceman
      POSTGRES_DB: movietracker
  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
  frontend:
    container_name: frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: ./apps/frontendVue/Dockerfile
      args:
        - VITE_BASE_URL=${VITE_BASE_URL}
        - VITE_API_URL=${VITE_API_URL}
        - VITE_TMDB_API_URL=${VITE_TMDB_API_URL}
        - VITE_TMDB_API_KEY=${VITE_TMDB_API_KEY}
    env_file: ./.env
  backend:
    container_name: backend
    restart: unless-stopped
    ports:
      - 1337:1337
    build:
      dockerfile: ./apps/backend/Dockerfile
    env_file: ./.env
    volumes:
      - sitemaps:/app/apps/backend/sitemaps


volumes:
  caddy_data:
  caddy_config:
  postgres-data:
  sitemaps:
