version: '3'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER:-spaceman}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-spaceman}
      POSTGRES_DB: movietracker
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8085:8080
volumes:
  postgres-data:
