version: '3'

services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
  frontend:
    image: danilavoronkov/movie-tracker-frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    build:
      context: ./

volumes:
  caddy_data:
  caddy_config:
