services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.7
    restart: on-failure
    environment:
      CLICKHOUSE_DB: uptrace
    healthcheck:
      test: [CMD, wget, --spider, -q, "localhost:8123/ping"]
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - ch_data2:/var/lib/clickhouse
    expose:
      - "8123"
      - "9000"
    networks:
      - uptrace
    deploy:
      placement:
        constraints:
          - node.role != manager
          - node.labels.databases != true

  postgres:
    image: postgres:15-alpine
    restart: on-failure
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: uptrace
      POSTGRES_PASSWORD: uptrace
      POSTGRES_DB: uptrace
    healthcheck:
      test: [CMD-SHELL, pg_isready -U uptrace -d uptrace]
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - "pg_data3:/var/lib/postgresql/data/pgdata"
    expose:
      - "5432"
    networks:
      - uptrace
    deploy:
      placement:
        constraints:
          - node.labels.databases == true

  uptrace:
    image: "uptrace/uptrace:1.7.5"
    # image: 'uptrace/uptrace-dev:latest'
    restart: on-failure
    configs:
      - source: uptrace_config
        target: /etc/uptrace/uptrace.yml
    # environment:
    #  - DEBUG=2
    expose:
      - 14317
      - 14318
    depends_on:
      - clickhouse
      - postgres
    networks:
      - uptrace
      - caddy-public
    deploy:
      placement:
        constraints:
          - node.role != manager
          - node.labels.databases != true

  otelcol:
    image: otel/opentelemetry-collector-contrib:0.88.0
    restart: on-failure
    configs:
      - source: otel_collector_config
        target: /etc/otelcol-contrib/config.yaml
    expose:
      - "4317"
      - "4318"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - uptrace
    networks:
      - uptrace
      - movie-tracker-metrics
    deploy:
      placement:
        constraints:
          - node.role != manager
          - node.labels.databases != true

  mailpit:
    image: axllent/mailpit
    restart: always
    expose:
      - 1025
      - 8025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    volumes:
      - mailpit_data:/data
    networks:
      - uptrace
    deploy:
      placement:
        constraints:
          - node.role != manager
          - node.labels.databases != true

  vector:
    image: timberio/vector:0.28.X-alpine
    configs:
      - source: vector_config
        target: /etc/vector/vector.toml
    networks:
      - uptrace
    deploy:
      placement:
        constraints:
          - node.role != manager
          - node.labels.databases != true

  #  grafana:
  #    image: grafana/grafana:9.5.3
  #    restart: on-failure
  #    volumes:
  #      - ../../config/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
  #      - ../../config/grafana/custom.ini:/etc/grafana/grafana.ini
  #    ports:
  #      - '3000:3000'
  #    extra_hosts:
  #      - 'host.docker.internal:host-gateway'
  #    networks:
  #      - uptrace

  #  prometheus:
  #    image: prom/prometheus:v2.36.2
  #    restart: always
  #    volumes:
  #      - ../../config/prometheus/:/etc/prometheus/
  #      - prometheus_data:/prometheus
  #    command:
  #      - --config.file=/etc/prometheus/prometheus.yml
  #      - --storage.tsdb.path=/prometheus
  #      - --web.console.libraries=/usr/share/prometheus/console_libraries
  #      - --web.console.templates=/usr/share/prometheus/consoles
  #    extra_hosts:
  #      - "host.docker.internal:host-gateway"
  #    networks:
  #      - uptrace

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - --path.rootfs=/host
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"
    deploy:
      placement:
        constraints:
          - node.role != manager
          - node.labels.databases != true

configs:
  uptrace_config:
    file: ./uptrace.yml
  otel_collector_config:
    file: ./otel-collector.yaml
  vector_config:
    file: ./vector.toml

volumes:
  ch_data2:
  pg_data3:
  prometheus_data:
  mailpit_data:

networks:
  uptrace:
    name: uptrace
  movie-tracker-metrics:
    name: movie-tracker-metrics
    external: true
  caddy-public:
    name: caddy-public
    external: true
