name: Build and push docker images

on:
  push:
    branches: [ 'master' ]
  workflow_dispatch:

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ./apps/frontendVue/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/movie-tracker-frontend:latest
          build-args: |
            VITE_BASE_URL=${{ secrets.BASE_URL }}
            VITE_API_URL=${{ secrets.API_URL }}
            VITE_TMDB_API_URL=${{ secrets.TMDB_API_URL }}
            VITE_TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ./apps/backend/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/movie-tracker-backend:latest
